// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowProfileParams creates a new ShowProfileParams object
// with the default values initialized.
func NewShowProfileParams() *ShowProfileParams {

	return &ShowProfileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowProfileParamsWithTimeout creates a new ShowProfileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowProfileParamsWithTimeout(timeout time.Duration) *ShowProfileParams {

	return &ShowProfileParams{

		timeout: timeout,
	}
}

// NewShowProfileParamsWithContext creates a new ShowProfileParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowProfileParamsWithContext(ctx context.Context) *ShowProfileParams {

	return &ShowProfileParams{

		Context: ctx,
	}
}

// NewShowProfileParamsWithHTTPClient creates a new ShowProfileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowProfileParamsWithHTTPClient(client *http.Client) *ShowProfileParams {

	return &ShowProfileParams{
		HTTPClient: client,
	}
}

/*ShowProfileParams contains all the parameters to send to the API endpoint
for the show profile operation typically these are written to a http.Request
*/
type ShowProfileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show profile params
func (o *ShowProfileParams) WithTimeout(timeout time.Duration) *ShowProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show profile params
func (o *ShowProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show profile params
func (o *ShowProfileParams) WithContext(ctx context.Context) *ShowProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show profile params
func (o *ShowProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show profile params
func (o *ShowProfileParams) WithHTTPClient(client *http.Client) *ShowProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show profile params
func (o *ShowProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ShowProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
