// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTokenProfileParams creates a new TokenProfileParams object
// with the default values initialized.
func NewTokenProfileParams() *TokenProfileParams {

	return &TokenProfileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTokenProfileParamsWithTimeout creates a new TokenProfileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTokenProfileParamsWithTimeout(timeout time.Duration) *TokenProfileParams {

	return &TokenProfileParams{

		timeout: timeout,
	}
}

// NewTokenProfileParamsWithContext creates a new TokenProfileParams object
// with the default values initialized, and the ability to set a context for a request
func NewTokenProfileParamsWithContext(ctx context.Context) *TokenProfileParams {

	return &TokenProfileParams{

		Context: ctx,
	}
}

// NewTokenProfileParamsWithHTTPClient creates a new TokenProfileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTokenProfileParamsWithHTTPClient(client *http.Client) *TokenProfileParams {

	return &TokenProfileParams{
		HTTPClient: client,
	}
}

/*TokenProfileParams contains all the parameters to send to the API endpoint
for the token profile operation typically these are written to a http.Request
*/
type TokenProfileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the token profile params
func (o *TokenProfileParams) WithTimeout(timeout time.Duration) *TokenProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the token profile params
func (o *TokenProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the token profile params
func (o *TokenProfileParams) WithContext(ctx context.Context) *TokenProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the token profile params
func (o *TokenProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the token profile params
func (o *TokenProfileParams) WithHTTPClient(client *http.Client) *TokenProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the token profile params
func (o *TokenProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TokenProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
