// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/umschlag/umschlag-go/models"
)

// UpdateProfileReader is a Reader for the UpdateProfile structure.
type UpdateProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewUpdateProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 412:
		result := NewUpdateProfilePreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewUpdateProfileUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewUpdateProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateProfileOK creates a UpdateProfileOK with default headers values
func NewUpdateProfileOK() *UpdateProfileOK {
	return &UpdateProfileOK{}
}

/*UpdateProfileOK handles this case with default header values.

The updated profile data
*/
type UpdateProfileOK struct {
	Payload *models.Profile
}

func (o *UpdateProfileOK) Error() string {
	return fmt.Sprintf("[PUT /profile/self][%d] updateProfileOK  %+v", 200, o.Payload)
}

func (o *UpdateProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Profile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProfileForbidden creates a UpdateProfileForbidden with default headers values
func NewUpdateProfileForbidden() *UpdateProfileForbidden {
	return &UpdateProfileForbidden{}
}

/*UpdateProfileForbidden handles this case with default header values.

User is not authorized
*/
type UpdateProfileForbidden struct {
	Payload *models.GeneralError
}

func (o *UpdateProfileForbidden) Error() string {
	return fmt.Sprintf("[PUT /profile/self][%d] updateProfileForbidden  %+v", 403, o.Payload)
}

func (o *UpdateProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProfilePreconditionFailed creates a UpdateProfilePreconditionFailed with default headers values
func NewUpdateProfilePreconditionFailed() *UpdateProfilePreconditionFailed {
	return &UpdateProfilePreconditionFailed{}
}

/*UpdateProfilePreconditionFailed handles this case with default header values.

Failed to parse request body
*/
type UpdateProfilePreconditionFailed struct {
	Payload *models.GeneralError
}

func (o *UpdateProfilePreconditionFailed) Error() string {
	return fmt.Sprintf("[PUT /profile/self][%d] updateProfilePreconditionFailed  %+v", 412, o.Payload)
}

func (o *UpdateProfilePreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProfileUnprocessableEntity creates a UpdateProfileUnprocessableEntity with default headers values
func NewUpdateProfileUnprocessableEntity() *UpdateProfileUnprocessableEntity {
	return &UpdateProfileUnprocessableEntity{}
}

/*UpdateProfileUnprocessableEntity handles this case with default header values.

Failed to validate request
*/
type UpdateProfileUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateProfileUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /profile/self][%d] updateProfileUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateProfileUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProfileDefault creates a UpdateProfileDefault with default headers values
func NewUpdateProfileDefault(code int) *UpdateProfileDefault {
	return &UpdateProfileDefault{
		_statusCode: code,
	}
}

/*UpdateProfileDefault handles this case with default header values.

Some error unrelated to the handler
*/
type UpdateProfileDefault struct {
	_statusCode int

	Payload *models.GeneralError
}

// Code gets the status code for the update profile default response
func (o *UpdateProfileDefault) Code() int {
	return o._statusCode
}

func (o *UpdateProfileDefault) Error() string {
	return fmt.Sprintf("[PUT /profile/self][%d] UpdateProfile default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
