// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRefreshAuthParams creates a new RefreshAuthParams object
// with the default values initialized.
func NewRefreshAuthParams() *RefreshAuthParams {

	return &RefreshAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRefreshAuthParamsWithTimeout creates a new RefreshAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRefreshAuthParamsWithTimeout(timeout time.Duration) *RefreshAuthParams {

	return &RefreshAuthParams{

		timeout: timeout,
	}
}

// NewRefreshAuthParamsWithContext creates a new RefreshAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewRefreshAuthParamsWithContext(ctx context.Context) *RefreshAuthParams {

	return &RefreshAuthParams{

		Context: ctx,
	}
}

// NewRefreshAuthParamsWithHTTPClient creates a new RefreshAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRefreshAuthParamsWithHTTPClient(client *http.Client) *RefreshAuthParams {

	return &RefreshAuthParams{
		HTTPClient: client,
	}
}

/*RefreshAuthParams contains all the parameters to send to the API endpoint
for the refresh auth operation typically these are written to a http.Request
*/
type RefreshAuthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the refresh auth params
func (o *RefreshAuthParams) WithTimeout(timeout time.Duration) *RefreshAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the refresh auth params
func (o *RefreshAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the refresh auth params
func (o *RefreshAuthParams) WithContext(ctx context.Context) *RefreshAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the refresh auth params
func (o *RefreshAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the refresh auth params
func (o *RefreshAuthParams) WithHTTPClient(client *http.Client) *RefreshAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the refresh auth params
func (o *RefreshAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RefreshAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
