// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVerifyAuthParams creates a new VerifyAuthParams object
// with the default values initialized.
func NewVerifyAuthParams() *VerifyAuthParams {
	var ()
	return &VerifyAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyAuthParamsWithTimeout creates a new VerifyAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVerifyAuthParamsWithTimeout(timeout time.Duration) *VerifyAuthParams {
	var ()
	return &VerifyAuthParams{

		timeout: timeout,
	}
}

// NewVerifyAuthParamsWithContext creates a new VerifyAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewVerifyAuthParamsWithContext(ctx context.Context) *VerifyAuthParams {
	var ()
	return &VerifyAuthParams{

		Context: ctx,
	}
}

// NewVerifyAuthParamsWithHTTPClient creates a new VerifyAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVerifyAuthParamsWithHTTPClient(client *http.Client) *VerifyAuthParams {
	var ()
	return &VerifyAuthParams{
		HTTPClient: client,
	}
}

/*VerifyAuthParams contains all the parameters to send to the API endpoint
for the verify auth operation typically these are written to a http.Request
*/
type VerifyAuthParams struct {

	/*Token
	  A token that have to be checked

	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the verify auth params
func (o *VerifyAuthParams) WithTimeout(timeout time.Duration) *VerifyAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify auth params
func (o *VerifyAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify auth params
func (o *VerifyAuthParams) WithContext(ctx context.Context) *VerifyAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify auth params
func (o *VerifyAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify auth params
func (o *VerifyAuthParams) WithHTTPClient(client *http.Client) *VerifyAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify auth params
func (o *VerifyAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the verify auth params
func (o *VerifyAuthParams) WithToken(token string) *VerifyAuthParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the verify auth params
func (o *VerifyAuthParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
