// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/umschlag/umschlag-go/models"
)

// ListUserTeamsReader is a Reader for the ListUserTeams structure.
type ListUserTeamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUserTeamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListUserTeamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewListUserTeamsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewListUserTeamsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListUserTeamsOK creates a ListUserTeamsOK with default headers values
func NewListUserTeamsOK() *ListUserTeamsOK {
	return &ListUserTeamsOK{}
}

/*ListUserTeamsOK handles this case with default header values.

A collection of user teams
*/
type ListUserTeamsOK struct {
	Payload []*models.TeamUser
}

func (o *ListUserTeamsOK) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/teams][%d] listUserTeamsOK  %+v", 200, o.Payload)
}

func (o *ListUserTeamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListUserTeamsForbidden creates a ListUserTeamsForbidden with default headers values
func NewListUserTeamsForbidden() *ListUserTeamsForbidden {
	return &ListUserTeamsForbidden{}
}

/*ListUserTeamsForbidden handles this case with default header values.

User is not authorized
*/
type ListUserTeamsForbidden struct {
	Payload *models.GeneralError
}

func (o *ListUserTeamsForbidden) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/teams][%d] listUserTeamsForbidden  %+v", 403, o.Payload)
}

func (o *ListUserTeamsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListUserTeamsDefault creates a ListUserTeamsDefault with default headers values
func NewListUserTeamsDefault(code int) *ListUserTeamsDefault {
	return &ListUserTeamsDefault{
		_statusCode: code,
	}
}

/*ListUserTeamsDefault handles this case with default header values.

Some error unrelated to the handler
*/
type ListUserTeamsDefault struct {
	_statusCode int

	Payload *models.GeneralError
}

// Code gets the status code for the list user teams default response
func (o *ListUserTeamsDefault) Code() int {
	return o._statusCode
}

func (o *ListUserTeamsDefault) Error() string {
	return fmt.Sprintf("[GET /users/{user_id}/teams][%d] ListUserTeams default  %+v", o._statusCode, o.Payload)
}

func (o *ListUserTeamsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
