// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowUserParams creates a new ShowUserParams object
// with the default values initialized.
func NewShowUserParams() *ShowUserParams {
	var ()
	return &ShowUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowUserParamsWithTimeout creates a new ShowUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowUserParamsWithTimeout(timeout time.Duration) *ShowUserParams {
	var ()
	return &ShowUserParams{

		timeout: timeout,
	}
}

// NewShowUserParamsWithContext creates a new ShowUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowUserParamsWithContext(ctx context.Context) *ShowUserParams {
	var ()
	return &ShowUserParams{

		Context: ctx,
	}
}

// NewShowUserParamsWithHTTPClient creates a new ShowUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowUserParamsWithHTTPClient(client *http.Client) *ShowUserParams {
	var ()
	return &ShowUserParams{
		HTTPClient: client,
	}
}

/*ShowUserParams contains all the parameters to send to the API endpoint
for the show user operation typically these are written to a http.Request
*/
type ShowUserParams struct {

	/*UserID
	  A user UUID or slug

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show user params
func (o *ShowUserParams) WithTimeout(timeout time.Duration) *ShowUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show user params
func (o *ShowUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show user params
func (o *ShowUserParams) WithContext(ctx context.Context) *ShowUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show user params
func (o *ShowUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show user params
func (o *ShowUserParams) WithHTTPClient(client *http.Client) *ShowUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show user params
func (o *ShowUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the show user params
func (o *ShowUserParams) WithUserID(userID string) *ShowUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the show user params
func (o *ShowUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ShowUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
