// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/umschlag/umschlag-go/models"
)

// NewCreateTeamParams creates a new CreateTeamParams object
// with the default values initialized.
func NewCreateTeamParams() *CreateTeamParams {
	var ()
	return &CreateTeamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTeamParamsWithTimeout creates a new CreateTeamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTeamParamsWithTimeout(timeout time.Duration) *CreateTeamParams {
	var ()
	return &CreateTeamParams{

		timeout: timeout,
	}
}

// NewCreateTeamParamsWithContext creates a new CreateTeamParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTeamParamsWithContext(ctx context.Context) *CreateTeamParams {
	var ()
	return &CreateTeamParams{

		Context: ctx,
	}
}

// NewCreateTeamParamsWithHTTPClient creates a new CreateTeamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTeamParamsWithHTTPClient(client *http.Client) *CreateTeamParams {
	var ()
	return &CreateTeamParams{
		HTTPClient: client,
	}
}

/*CreateTeamParams contains all the parameters to send to the API endpoint
for the create team operation typically these are written to a http.Request
*/
type CreateTeamParams struct {

	/*Team
	  The team data to create

	*/
	Team *models.Team

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create team params
func (o *CreateTeamParams) WithTimeout(timeout time.Duration) *CreateTeamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create team params
func (o *CreateTeamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create team params
func (o *CreateTeamParams) WithContext(ctx context.Context) *CreateTeamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create team params
func (o *CreateTeamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create team params
func (o *CreateTeamParams) WithHTTPClient(client *http.Client) *CreateTeamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create team params
func (o *CreateTeamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeam adds the team to the create team params
func (o *CreateTeamParams) WithTeam(team *models.Team) *CreateTeamParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the create team params
func (o *CreateTeamParams) SetTeam(team *models.Team) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTeamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Team != nil {
		if err := r.SetBodyParam(o.Team); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
