// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/umschlag/umschlag-go/models"
)

// NewDelteTeamFromUserParams creates a new DelteTeamFromUserParams object
// with the default values initialized.
func NewDelteTeamFromUserParams() *DelteTeamFromUserParams {
	var ()
	return &DelteTeamFromUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDelteTeamFromUserParamsWithTimeout creates a new DelteTeamFromUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDelteTeamFromUserParamsWithTimeout(timeout time.Duration) *DelteTeamFromUserParams {
	var ()
	return &DelteTeamFromUserParams{

		timeout: timeout,
	}
}

// NewDelteTeamFromUserParamsWithContext creates a new DelteTeamFromUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewDelteTeamFromUserParamsWithContext(ctx context.Context) *DelteTeamFromUserParams {
	var ()
	return &DelteTeamFromUserParams{

		Context: ctx,
	}
}

// NewDelteTeamFromUserParamsWithHTTPClient creates a new DelteTeamFromUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDelteTeamFromUserParamsWithHTTPClient(client *http.Client) *DelteTeamFromUserParams {
	var ()
	return &DelteTeamFromUserParams{
		HTTPClient: client,
	}
}

/*DelteTeamFromUserParams contains all the parameters to send to the API endpoint
for the delte team from user operation typically these are written to a http.Request
*/
type DelteTeamFromUserParams struct {

	/*TeamID
	  A team UUID or slug

	*/
	TeamID string
	/*TeamUser
	  The team user data to delete

	*/
	TeamUser *models.TeamUserParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delte team from user params
func (o *DelteTeamFromUserParams) WithTimeout(timeout time.Duration) *DelteTeamFromUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delte team from user params
func (o *DelteTeamFromUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delte team from user params
func (o *DelteTeamFromUserParams) WithContext(ctx context.Context) *DelteTeamFromUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delte team from user params
func (o *DelteTeamFromUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delte team from user params
func (o *DelteTeamFromUserParams) WithHTTPClient(client *http.Client) *DelteTeamFromUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delte team from user params
func (o *DelteTeamFromUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the delte team from user params
func (o *DelteTeamFromUserParams) WithTeamID(teamID string) *DelteTeamFromUserParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the delte team from user params
func (o *DelteTeamFromUserParams) SetTeamID(teamID string) {
	o.TeamID = teamID
}

// WithTeamUser adds the teamUser to the delte team from user params
func (o *DelteTeamFromUserParams) WithTeamUser(teamUser *models.TeamUserParams) *DelteTeamFromUserParams {
	o.SetTeamUser(teamUser)
	return o
}

// SetTeamUser adds the teamUser to the delte team from user params
func (o *DelteTeamFromUserParams) SetTeamUser(teamUser *models.TeamUserParams) {
	o.TeamUser = teamUser
}

// WriteToRequest writes these params to a swagger request
func (o *DelteTeamFromUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param team_id
	if err := r.SetPathParam("team_id", o.TeamID); err != nil {
		return err
	}

	if o.TeamUser != nil {
		if err := r.SetBodyParam(o.TeamUser); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
