// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListTeamUsersParams creates a new ListTeamUsersParams object
// with the default values initialized.
func NewListTeamUsersParams() *ListTeamUsersParams {
	var ()
	return &ListTeamUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListTeamUsersParamsWithTimeout creates a new ListTeamUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListTeamUsersParamsWithTimeout(timeout time.Duration) *ListTeamUsersParams {
	var ()
	return &ListTeamUsersParams{

		timeout: timeout,
	}
}

// NewListTeamUsersParamsWithContext creates a new ListTeamUsersParams object
// with the default values initialized, and the ability to set a context for a request
func NewListTeamUsersParamsWithContext(ctx context.Context) *ListTeamUsersParams {
	var ()
	return &ListTeamUsersParams{

		Context: ctx,
	}
}

// NewListTeamUsersParamsWithHTTPClient creates a new ListTeamUsersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListTeamUsersParamsWithHTTPClient(client *http.Client) *ListTeamUsersParams {
	var ()
	return &ListTeamUsersParams{
		HTTPClient: client,
	}
}

/*ListTeamUsersParams contains all the parameters to send to the API endpoint
for the list team users operation typically these are written to a http.Request
*/
type ListTeamUsersParams struct {

	/*TeamID
	  A team UUID or slug

	*/
	TeamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list team users params
func (o *ListTeamUsersParams) WithTimeout(timeout time.Duration) *ListTeamUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list team users params
func (o *ListTeamUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list team users params
func (o *ListTeamUsersParams) WithContext(ctx context.Context) *ListTeamUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list team users params
func (o *ListTeamUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list team users params
func (o *ListTeamUsersParams) WithHTTPClient(client *http.Client) *ListTeamUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list team users params
func (o *ListTeamUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the list team users params
func (o *ListTeamUsersParams) WithTeamID(teamID string) *ListTeamUsersParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the list team users params
func (o *ListTeamUsersParams) SetTeamID(teamID string) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *ListTeamUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param team_id
	if err := r.SetPathParam("team_id", o.TeamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
